[project]
name = "movie-catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "redis[hiredis]>=6.4.0",
    "typer>=0.17.4",
]
